name: "ci"

on:
  push:
    branches:
      - "main"
  pull_request_target:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/gem_ci.yml@main"
    secrets: "inherit"
